### PR TITLE
JSX support and improved npm run tasks

### PR DESCRIPTION
**Pull request by konsumer**
This resolves 3 things:

* `npm test` is traditionally used for unit-tests. `npm start` is often used for a dev-server.
* `npm start` wasn't running initial build before watch.
* Added JSX support, demo & updated README

I also readded a `npm test`, so travis would try a build to test (which is better than running a dev server) but then realized that the .travis.yml does that anyway.

### CODE REVIEW

**Comment by konsumer** [comment]
Hmm. not sure why it's failing.

**Comment by yamafaktory** [comment]
Hi konsumer and thanks for the PR.

The first build failed as the latest version of your plugin wasn't published on npm. I've rerun the tests and now another error is thrown. I'm pretty sure it's related to https://github.com/rollup/rollup-plugin-commonjs/issues/63 which involves node v6.0.0 (used in the CI tests). Could you modify your PR in order to use node v5.11.1 instead in the `.travis.yml` file?

**Comment by konsumer** [comment]
I could, but I am using 6.0.0 locally (I noticed you had it set to that, so I switched with nvm) and it works fine.

**Comment by konsumer** [comment]
Problem with Travis?

**Comment by yamafaktory** [comment]
In fact, Travis is totally right. I just need to adjust the `config/prod.js` file! Thanks for your work :beers:

**Comment by konsumer** [comment]
Nice!

**Comment by konsumer** [comment]
Just noticed that `rollup-plugin-jsx` isn't pulled in anymore, but jsx still works. Is that plugin unneeded now?

**Comment by konsumer** [comment]
[Found it](https://github.com/yamafaktory/buble-react-rollup-starter/commit/0ba9da0f185c66774f4197df65eea70b46df9af9)! Sweet.

**Pull request merged**
